org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_version=1.0.0
mod_id=better-inventory
maven_group=cc.spea.betterinventory
archives_name=better-inventory

minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_api_version=0.158.0+26.2
architectury_version=21.0.7
junit_version=5.12.2
assertj_version=3.27.3
